export const LOAD_ISSUES = 'LOAD_ISSUES';
export const LOAD_ISSUES_SUCCESS = 'LOAD_ISSUES_SUCCESS';
export const LOAD_ISSUES_FAILURE = 'LOAD_ISSUES_FAILURE';

export const LOAD_ISSUE = 'LOAD_ISSUE';
export const LOAD_ISSUE_SUCCESS = 'LOAD_ISSUE_SUCCESS';
export const LOAD_ISSUE_FAILURE = 'LOAD_ISSUE_FAILURE';

export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';