export const LOAD_ISSUES = 'LOAD_ISSUES';
export const LOAD_ISSUES_SUCCESS = 'LOAD_ISSUES_SUCCESS';
export const LOAD_ISSUES_ERROR = 'LOAD_ISSUES_ERROR';

export const LOAD_ISSUE = 'LOAD_ISSUE';
export const LOAD_ISSUE_SUCCESS = 'LOAD_ISSUE_SUCCESS';
export const LOAD_ISSUE_ERROR = 'LOAD_ISSUE_ERROR';

export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';